src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank]
    #[Assert\GreaterThanOrEqual(20)]
    private ?int $horsepower = null;

    #[ORM\Column(nullable: true)]
    #[Assert\NotBlank]
    private ?\DateTimeImmutable $releasedAt = null;

    #[ORM\Column(length: 50)]
    private ?string $Color = null;

    #[ORM\ManyToOne(inversedBy: 'car')]
    #[Assert\NotBlank]
    private ?Brand $brand = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getHorsepower(): ?int
    {
        return $this->horsepower;
    }

    public function setHorsepower(?int $horsepower): static
    {
        $this->horsepower = $horsepower;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeImmutable
    {
        return $this->releasedAt;
    }

    public function setReleasedAt(?\DateTimeImmutable $releasedAt): static
    {
        $this->releasedAt = $releasedAt;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): static
    {
        $this->Color = $Color;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Brand;
use App\Entity\Car;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                "label" => "Nom du modèle"
            ])
            ->add('horsepower', IntegerType::class, [
                "label" => "Puissance"
            ])
            ->add('releasedAt', DateType::class, [
                'widget' => 'single_text',
                "label" => "Date de sortie"
            ])
            ->add('Color', TextType::class, [
                "label" => "Couleur"
            ])
            ->add('brand', EntityType::class, [
                'class' => Brand::class,
                'choice_label' => 'name',
                'expanded'=> false ,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CarController extends AbstractController
{
    #[Route('/', name: 'app_car_browse')]
    public function index(CarRepository $carRepo): Response
    {
        $carList = $carRepo->findAll();
        return $this->render('car/browse.html.twig', [
            "carList" => $carList
        ]);
    }

    #[Route('/{id<\d+>}', name: 'app_car_read', methods:"GET")]
    public function read(Car $car): Response
    {
        return $this->render('car/read.html.twig', [
            "car" => $car
        ]);
    }

    #[Route('/{id<\d+>}/edit', name: 'app_car_edit', methods:['GET', 'POST'])]
    public function edit(EntityManagerInterface $em, Request $request, Car $car): Response
    {
        $form = $this->createForm(CarType::class, $car);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $em->flush();
            $this->addFlash('success', 'Voiture modifié avec succès');

            return $this->redirectToRoute('app_car_read', ['id' => $car->getId()]);
        }

        return $this->render('car/edit.html.twig', [
            'form' => $form,
            'car' => $car,
        ]);
    }

    #[Route('/{id<\d+>}/delete', name: 'app_car_delete', methods:'GET')]
    public function delete(EntityManagerInterface $em, Car $car): Response
    {
        $em->remove($car);

        $em->flush();

        $this->addFlash('success', 'Suppression réussie');

        return $this->redirectToRoute('app_car_browse');
    }

    #[Route('/add', name: 'app_car_add', methods:['GET', 'POST'])]
    public function add(EntityManagerInterface $em, Request $request): Response
    {
        $car = new Car();

        $form = $this->createForm(CarType::class, $car);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $em->persist($car);
            $em->flush();

            $this->addFlash('success', 'Voiture ajouté avec succès');
            
            return $this->redirectToRoute('app_car_browse');
        }

        return $this->render('car/add.html.twig', [
            'form' => $form,
            'car' => $car,
        ]);
    }
}

templates/car/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une voiture{% endblock %}

{% block body %}
    <div class="container-xl bg-light p-5 border-top">

        
        <h1>Ajouter une voiture</h1>

        {{ form_start(form, {"attr": {"novalidate" : "novalidate"}}) }}
        {{ form_row(form) }}
        <button class="btn btn-primary">Ajouter la voiture</button>
        {{ form_end(form) }}

    <a href="{{ path('app_car_browse') }}" class="nav-link">Retour à la liste</a>
    </div>
{% endblock %}

templates/car/browse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des voitures{% endblock %}

{% block body %}
    <div class="container-xl bg-light p-5 border-top">

        <h1>Liste des voitures</h1>

        <a href="{{ path('app_car_add') }}" class="btn btn-primary">Ajouter</a>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Modéle</th>
                    <th>Marque</th>
                    <th>Chevaux</th>
                    <th>Couleur</th>
                    <th>Date de sortie</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for currentCar in carList %}
                    <tr>
                        <td>{{ currentCar.id }}</td>
                        <td>{{ currentCar.name }}</td>
                        <td>{{ currentCar.brand.name }}</td>
                        <td>{{ currentCar.horsepower }}</td>
                        <td>{{ currentCar.color }}</td>
                        <td>{{ currentCar.releasedAt|date("m/d/Y") }}</td>
                        <td>
                            <a href="{{path('app_car_read', {id: currentCar.id})}}" class="btn btn-secondary">Détails</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ car.name }}{% endblock %}

{% block body %}
    <div class="container-xl bg-light p-5 border-top">

        
        <h1>Modifier {{ car.name }}</h1>

        {{ form_start(form, {"attr": {"novalidate" : "novalidate"}}) }}
        {{ form_row(form) }}
        <button class="btn btn-primary">Accepter</button>
        {{ form_end(form) }}

    <a href="{{ path('app_car_browse') }}" class="nav-link">Retour à la liste</a>
    </div>
{% endblock %}

templates/car/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de {{car.brand.name}} {{car.name}}{% endblock %}

{% block body %}
    <div class="container-xl bg-light p-5 border-top">

    <h1>{{car.brand.name}} {{car.name}}</h1>

    
    <a class="btn btn-primary" href="{{path("app_car_edit", {id: car.id} )}}">Modifier</a>
    <a class="btn btn-danger" href="{{path("app_car_delete", {id: car.id} )}}">Supprimer</a>
    <table class="table">
        <tbody>
            <tr><th>Id</th><td>{{ car.id }}</td></tr>
            <tr><th>Modéle</th><td>{{ car.name }}</td></tr>
            <tr><th>Marque</th><td>{{ car.brand.name }}</td></tr>   
            <tr><th>Chevaux</th><td>{{ car.horsepower }}</td></tr>
            <tr><th>Date de sortie</th><td>{{ car.releasedAt|date("m/d/Y") }}</td></tr>
            <tr><th>Color</th><td>{{ car.color }}</td></tr>
        </tbody>
    </table>
    <a class="nav-link" href="{{path("app_car_browse")}}">Retour à la liste</a>
    </div>
{% endblock %}